
spring:
  profiles: dev,default
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: user
    password: password
    url: jdbc:mysql://localhost:3306/PROCESSOS?useSSL=false
  jpa:
    hibernate.ddl-auto: update

    generate-ddl: true
    show-sql: false


